apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-django-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-django
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.django.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
