apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-k8s
data:
  DEBUG: "0"
  REGION: "India"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "hello@hobbiate.com"
  DJANGO_SECRET_KEY: "fix_this_later"
  ENV_ALLOWED_HOSTS: "127.0.0.1,localhost,0.0.0.0,localhost:8001"
  POSTGRES_DB: "dockerdc"
  POSTGRES_HOST: "postgres-db"
  POSTGRES_PORT: "5433"

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-k8s
type: Opaque
stringData:
  DJANGO_SUPERUSER_PASSWORD: "mydjangopw"
  POSTGRES_PASSWORD: "mysecretpw"
  POSTGRES_USER: "myuser"
